export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$HOME/dotfiles/config/zsh

ZSH_THEME="xxf"

source $ZSH/oh-my-zsh.sh

export LANG=C
export EDITOR="nvim"

# Source Custom Configurations <<1
for fname in $(find ~/dotfiles/custom-configs -name "*.sh*"); do
  source $fname
done
# >>1

. /opt/homebrew/opt/asdf/libexec/asdf.sh
