export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$HOME/dotfiles/config/zsh

ZSH_THEME="headline"

source $ZSH/oh-my-zsh.sh

export LANG=C
export EDITOR="nvim"

# Source Custom Configurations <<1
for fname in $(find ~/dotfiles/custom-configs -name "*.sh*"); do
  source $fname
done
# >>1

export PATH="$PATH:/Users/nickel/.local/bin:/opt/homebrew/opt/awscli@1/bin"
if [ -f "/Users/nickel/.config/fabric/fabric-bootstrap.inc" ]; then . "/Users/nickel/.config/fabric/fabric-bootstrap.inc"; fi
